const K={entries:'mqpx_entries_v1',settings:'mqpx_settings_v1',goals:'mqpx_goals_v1',xp:'mqpx_xp_v1'};
const DEFAULT_SETTINGS={gross:66000,inHand:60000,otherIncome:0,savingsTarget:8000,rent:23000,furniture:2000,wifi:499,wifiFrom:'2026-09',momTarget:10000,protectMom:false,limits:{food:4000,shopping:3500,transport:6000,other:2500}};
const DEFAULT_GOALS=[{name:'Emergency Fund',target:60000,saved:0},{name:'Travel Fund',target:30000,saved:0},{name:'Meta Glasses Fund',target:70000,saved:0},{name:'First Salary Treats',target:6000,saved:0},{name:'Mom Bucket',target:10000,saved:0}];
const CATS={expense:['Food Delivery','Office Food','Groceries','Transport','Rent','Furniture Rent','WiFi','Shopping','Health','Beauty','Travel','Other'],income:['Salary','Refund','Other Income'],saving:DEFAULT_GOALS.map(g=>g.name),breakfast:['Office Breakfast','Coffee','Snack']};
const LEVELS=['Rookie Tracker','Coin Scout','Budget Fighter','Spend Slayer','Savings Knight','Cash Strategist','Risk Hunter','Money Mage','Wealth Guardian','Finance Legend'];
let state={entries:load(K.entries,[]),settings:load(K.settings,DEFAULT_SETTINGS),goals:load(K.goals,DEFAULT_GOALS),xp:load(K.xp,0)};
const $=id=>document.getElementById(id);
const clone=o=>JSON.parse(JSON.stringify(o));
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??clone(fallback)}catch{return clone(fallback)}}
function save(){localStorage.setItem(K.entries,JSON.stringify(state.entries));localStorage.setItem(K.settings,JSON.stringify(state.settings));localStorage.setItem(K.goals,JSON.stringify(state.goals));localStorage.setItem(K.xp,JSON.stringify(state.xp))}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Math.round(v||0))}
function today(){return new Date().toISOString().slice(0,10)}
function monthKey(d=new Date()){return d.toISOString().slice(0,7)}
function sum(a){return a.reduce((x,y)=>x+Number(y||0),0)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmt(d){return new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}
function monthEntries(){return state.entries.filter(e=>e.date.startsWith(monthKey()))}
function isWifiActive(){return monthKey()>=state.settings.wifiFrom}
function daysLeft(){const n=new Date();const last=new Date(n.getFullYear(),n.getMonth()+1,0).getDate();return Math.max(1,last-n.getDate()+1)}
function init(){bind();setToday();fillForms();populateCats();populateGoals();render()}
function bind(){
 document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>screen(b.dataset.screen,b));
 document.querySelectorAll('.type-tab').forEach(b=>b.onclick=()=>setType(b.dataset.type,b));
 document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>addEntry({id:crypto.randomUUID(),date:today(),type:b.dataset.type,category:b.dataset.category,title:b.dataset.title,amount:+b.dataset.amount,label:b.dataset.label,note:''}));
 $('entryForm').onsubmit=entrySubmit;$('goalForm').onsubmit=goalSubmit;$('incomeForm').onsubmit=incomeSubmit;$('fixedForm').onsubmit=fixedSubmit;$('limitForm').onsubmit=limitSubmit;$('momForm').onsubmit=momSubmit;
 $('noteToggle').onclick=()=>$('noteField').classList.toggle('hidden');
 $('sampleBtn').onclick=sample;$('backupBtn').onclick=backup;$('importInput').onchange=importBackup;$('csvBtn').onclick=csv;$('summaryBtn').onclick=summary;$('resetMonthBtn').onclick=resetMonth;$('resetAllBtn').onclick=resetAll;
 $('searchInput').oninput=renderHistory;$('filterType').onchange=renderHistory;
}
function screen(id,btn){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav-btn').forEach(n=>n.classList.remove('active'));btn.classList.add('active')}
function setType(type,btn){$('entryType').value=type;document.querySelectorAll('.type-tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');populateCats()}
function populateCats(){const t=$('entryType').value;$('entryCategory').innerHTML=CATS[t].map(c=>`<option value="${c}">${c}</option>`).join('')}
function populateGoals(){$('goalName').innerHTML=state.goals.map(g=>`<option value="${g.name}">${g.name}</option>`).join('')}
function setToday(){$('entryDate').value=today()}
function fillForms(){const s=state.settings;$('grossInput').value=s.gross;$('inHandInput').value=s.inHand;$('otherIncomeInput').value=s.otherIncome;$('savingsTargetInput').value=s.savingsTarget;$('rentInput').value=s.rent;$('furnitureInput').value=s.furniture;$('wifiInput').value=s.wifi;$('wifiMonthInput').value=s.wifiFrom;$('foodLimitInput').value=s.limits.food;$('shoppingLimitInput').value=s.limits.shopping;$('transportLimitInput').value=s.limits.transport;$('otherLimitInput').value=s.limits.other;$('momTargetInput').value=s.momTarget;$('protectMomInput').checked=!!s.protectMom}
function entrySubmit(e){e.preventDefault();const entry={id:crypto.randomUUID(),date:$('entryDate').value,type:$('entryType').value,category:$('entryCategory').value,amount:+$('entryAmount').value,title:$('entryTitle').value.trim(),label:$('entryLabel').value,note:$('entryNote').value.trim()};if(!entry.title||entry.amount<0)return toast('Check entry');addEntry(entry);e.target.reset();setToday();$('entryType').value='expense';document.querySelectorAll('.type-tab').forEach(t=>t.classList.toggle('active',t.dataset.type==='expense'));populateCats();$('noteField').classList.add('hidden')}
function xpFor(e){let x=20;if(e.type==='saving')x+=40;if(e.type==='income')x+=30;if(e.label==='Smart')x+=20;if(e.label==='Necessary')x+=10;if(['Rent','Furniture Rent','WiFi'].includes(e.category))x+=20;if(e.label==='Impulse'||e.label==='Regret')x-=5;return Math.max(5,x)}
function addEntry(e){state.entries.unshift(e);if(e.type==='saving'){const g=state.goals.find(x=>x.name===e.category);if(g)g.saved+=e.amount}const xp=xpFor(e);state.xp+=xp;save();render();spark();toast(`Saved +${xp} XP`)}
function goalSubmit(e){e.preventDefault();const amount=+$('goalAmount').value;if(amount<=0)return toast('Enter amount');addEntry({id:crypto.randomUUID(),date:today(),type:'saving',category:$('goalName').value,amount,title:`${$('goalName').value}`,label:'Smart',note:''});$('goalAmount').value=''}
function incomeSubmit(e){e.preventDefault();Object.assign(state.settings,{gross:+$('grossInput').value,inHand:+$('inHandInput').value,otherIncome:+$('otherIncomeInput').value,savingsTarget:+$('savingsTargetInput').value});save();render();toast('Saved')}
function fixedSubmit(e){e.preventDefault();Object.assign(state.settings,{rent:+$('rentInput').value,furniture:+$('furnitureInput').value,wifi:+$('wifiInput').value,wifiFrom:$('wifiMonthInput').value});save();render();toast('Saved')}
function limitSubmit(e){e.preventDefault();state.settings.limits={food:+$('foodLimitInput').value,shopping:+$('shoppingLimitInput').value,transport:+$('transportLimitInput').value,other:+$('otherLimitInput').value};save();render();toast('Saved')}
function momSubmit(e){e.preventDefault();state.settings.momTarget=+$('momTargetInput').value;state.settings.protectMom=$('protectMomInput').checked;const g=state.goals.find(x=>x.name==='Mom Bucket');if(g)g.target=state.settings.momTarget;save();render();toast('Saved')}
function calc(){
 const m=monthEntries(),s=state.settings,ex=m.filter(e=>e.type==='expense'||e.type==='breakfast'),inc=m.filter(e=>e.type==='income'),sav=m.filter(e=>e.type==='saving');
 const income=s.inHand+s.otherIncome+sum(inc.map(e=>e.amount));
 const fixedDue=s.rent+s.furniture+(isWifiActive()?s.wifi:0);
 const rentPaid=sum(ex.filter(e=>e.category==='Rent').map(e=>e.amount));const furniturePaid=sum(ex.filter(e=>e.category==='Furniture Rent').map(e=>e.amount));const wifiPaid=sum(ex.filter(e=>e.category==='WiFi').map(e=>e.amount));
 const fixedPaid=rentPaid+furniturePaid+wifiPaid;const fixedLeft=Math.max(0,s.rent-rentPaid)+Math.max(0,s.furniture-furniturePaid)+(isWifiActive()?Math.max(0,s.wifi-wifiPaid):0);
 const spent=sum(ex.map(e=>e.amount)),saved=sum(sav.map(e=>e.amount)),personalSaved=sum(sav.filter(e=>e.category!=='Mom Bucket').map(e=>e.amount)),momSaved=sum(sav.filter(e=>e.category==='Mom Bucket').map(e=>e.amount));
 const variableSpent=Math.max(0,spent-fixedPaid);const moneyLeft=income-spent-saved;const remainingSavings=Math.max(0,s.savingsTarget-personalSaved);const momProtected=s.protectMom?Math.max(0,s.momTarget-momSaved):0;const safePool=moneyLeft-fixedLeft-remainingSavings-momProtected;const safeDay=safePool/daysLeft();
 const totals={};ex.forEach(e=>totals[e.category]=(totals[e.category]||0)+e.amount);const food=sum(ex.filter(e=>e.category==='Food Delivery'||/zomato|zepto|blinkit|food/i.test(`${e.title} ${e.category}`)).map(e=>e.amount));const shopping=(totals.Shopping||0)+(totals.Beauty||0);const transport=totals.Transport||0;const other=(totals.Other||0)+sum(ex.filter(e=>e.label==='Impulse'||e.label==='Regret').map(e=>e.amount));
 const todayEntries=state.entries.filter(e=>e.date===today()),todayFood=sum(todayEntries.filter(e=>e.category==='Food Delivery'||/zomato|zepto|blinkit|food/i.test(`${e.title} ${e.category}`)).map(e=>e.amount));
 const streak=getStreak();const risks=riskData({food,shopping,transport,other,fixedLeft,fixedDue});const maxRisk=risks.reduce((a,b)=>b.score>a.score?b:a,{score:0,status:'LOW',name:'None'});
 const projected=safePool;return{m,ex,inc,sav,income,fixedDue,fixedPaid,fixedLeft,spent,saved,personalSaved,momSaved,variableSpent,moneyLeft,remainingSavings,momProtected,safePool,safeDay,totals,food,shopping,transport,other,todayEntries,todayFood,streak,risks,maxRisk,projected}
}
function riskData(v){const s=state.settings;const arr=[['Snack Risk','Food apps',v.food,s.limits.food,'No Food App'],['Shopping Risk','Shopping',v.shopping,s.limits.shopping,'Wait 24h'],['Commute Risk','Transport',v.transport,s.limits.transport,'Use Metro'],['Bill Boss','Fixed left',v.fixedLeft,Math.max(1,v.fixedDue),'Pay fixed'],['Chaos Risk','Other',v.other,s.limits.other,'Categorise']];return arr.map(([name,cat,amt,lim,action])=>{const pct=lim?amt/lim:0;const status=pct>=1?'BOSS':pct>=.8?'HIGH':pct>=.5?'WATCH':'SAFE';return{name,cat,amt,lim,action,pct:Math.min(1.3,pct),status,score:pct}})}
function getStreak(){const set=new Set(state.entries.map(e=>e.date));let d=new Date(),n=0;while(set.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function level(){const lv=Math.min(10,Math.floor(state.xp/1000)+1);const cur=state.xp-(lv-1)*1000;return{lv,name:LEVELS[lv-1],cur:Math.min(cur,1000),pct:Math.min(100,cur/1000*100)}}
function render(){const c=calc(),l=level();renderHome(c,l);renderTerminal(c,l);renderRisks(c);renderMissions(c);renderVault(c);renderInventory(c,l);renderHistory();fillForms();populateGoals()}
function renderHome(c,l){$('sideLevel').textContent=l.lv;$('sideLevelName').textContent=l.name;$('sideXpFill').style.width=l.pct+'%';$('homeLevelText').textContent=`Lv. ${l.lv} ${l.name}`;$('homeMoneyLeft').textContent=money(c.moneyLeft);$('homeSafeSpend').textContent=money(Math.max(0,c.safeDay));$('homeRisk').textContent=c.maxRisk.status;$('homeFixed').textContent=money(c.fixedDue);$('homeSaved').textContent=money(c.saved);$('homeXpFill').style.width=l.pct+'%';$('homeXpText').textContent=`${l.cur}/1000`;renderToday(c)}
function renderToday(c){$('todayMissions').innerHTML=dailyMissions(c).slice(0,3).map(m=>`<div class="mini-card"><b>${m.done?'DONE':'TODO'} · ${m.name}</b><span>+${m.xp} XP</span></div>`).join('');$('todayEntries').innerHTML=c.todayEntries.length?c.todayEntries.slice(0,4).map(e=>`<div class="entry-mini"><b>${esc(e.title)}</b><span>${money(e.amount)}</span></div>`).join(''):'<div class="entry-mini"><b>No logs</b><span>Today</span></div>'}
function renderTerminal(c,l){const rows=[['Money Left',money(c.moneyLeft),'after logs'],['Safe / Day',money(Math.max(0,c.safeDay)),`${daysLeft()} days`],['Income',money(c.income),'this month'],['Fixed Left',money(c.fixedLeft),'rent/furniture/wifi'],['Saved',money(c.personalSaved),`target ${money(state.settings.savingsTarget)}`],['Mom Bucket',money(c.momSaved),'separate'],['Projected',money(c.projected),'after protection'],['Risk',c.maxRisk.status,c.maxRisk.name],['Level',`Lv. ${l.lv}`,l.name],['XP',state.xp.toLocaleString('en-IN'),'total'],['Food Apps',money(c.food),'limit '+money(state.settings.limits.food)],['Variable',money(c.variableSpent),'spent']];$('terminalGrid').innerHTML=rows.map(r=>`<article class="term-card"><span>${r[0]}</span><strong>${r[1]}</strong><small>${r[2]}</small></article>`).join('')}
function renderRisks(c){$('riskGrid').innerHTML=c.risks.map(r=>`<article class="risk-card ${r.status==='BOSS'?'boss':r.status==='HIGH'?'high':'safe'}"><b>${r.name}</b><strong>${r.status}</strong><span>${money(r.amt)} / ${money(r.lim)}</span><div class="meter"><i style="width:${Math.min(100,r.pct*100)}%"></i></div><small>${r.action}</small></article>`).join('')}
function dailyMissions(c){return[{name:'Log Today',done:c.todayEntries.length>0,xp:20},{name:'No Food App',done:c.todayEntries.length>0&&c.todayFood===0,xp:25},{name:'Add Saving',done:c.todayEntries.some(e=>e.type==='saving'),xp:40},{name:'No Impulse',done:c.todayEntries.length>0&&!c.todayEntries.some(e=>e.label==='Impulse'||e.label==='Regret'),xp:30},{name:'Safe Day',done:c.safeDay>=0,xp:25}]}
function weeklyMissions(c){const week=last7();const saved=sum(week.filter(e=>e.type==='saving'&&e.category!=='Mom Bucket').map(e=>e.amount));const food=sum(week.filter(e=>e.category==='Food Delivery'||/zomato|zepto|blinkit|food/i.test(`${e.title} ${e.category}`)).map(e=>e.amount));const impulse=week.filter(e=>e.label==='Impulse'||e.label==='Regret').length;return[{name:'5-Day Streak',done:c.streak>=5,xp:150},{name:'Save ₹2k',done:saved>=2000,xp:120},{name:'Food < ₹1k',done:week.length>0&&food<=1000,xp:100},{name:'No Impulse',done:week.length>0&&impulse===0,xp:120}]}
function last7(){const set=new Set();for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);set.add(d.toISOString().slice(0,10))}return state.entries.filter(e=>set.has(e.date))}
function renderMissions(c){$('dailyMissionList').innerHTML=dailyMissions(c).map(mission).join('');$('weeklyMissionList').innerHTML=weeklyMissions(c).map(mission).join('')}
function mission(m){return`<div class="mission-card"><b>${m.done?'DONE':'TODO'} · ${m.name}</b><span>+${m.xp} XP</span></div>`}
function renderVault(c){$('goalGrid').innerHTML=state.goals.filter(g=>g.name!=='Mom Bucket').map(goalCard).join('');const mom=state.goals.find(g=>g.name==='Mom Bucket')||{saved:0,target:state.settings.momTarget};$('momBucket').innerHTML=`<b>Mom Bucket</b><strong>${money(mom.saved)} / ${money(state.settings.momTarget)}</strong><div class="meter"><i style="width:${Math.min(100,mom.saved/state.settings.momTarget*100)}%"></i></div><small>${state.settings.protectMom?'Protected':'Not Fixed'}</small>`}
function goalCard(g){const p=Math.min(100,g.saved/g.target*100);return`<div class="goal-card"><b>${g.name}</b><strong>${money(g.saved)}</strong><span>${money(g.target)}</span><div class="meter"><i style="width:${p}%"></i></div></div>`}
function renderInventory(c,l){const chars=[['Profile Girl','Main','girl',true],['Mochi','Pet','mochi',true],['Panda Pockets','Balance','panda',c.moneyLeft>=0&&c.m.length>0],['Penny','Savings','penny',c.saved>0],['Snack Monster','Food','monster',c.food>0],['Shopping Goblin','Shopping','goblin',c.shopping>0],['Cab Beast','Commute','cab',c.transport>0],['Bill Dragon','Fixed','dragon',c.fixedDue>0],['Budget Owl','Tips','owl',c.maxRisk.status!=='SAFE'],['Streak Squirrel','Streak','squirrel',c.streak>=3]];$('charGrid').innerHTML=chars.map(([n,r,sp,u])=>inv(n,r,sp,u)).join('');const items=[['Coin Pouch','First save',c.saved>0],['House Token','Rent set',state.settings.rent>0],['Sofa Token','Furniture set',state.settings.furniture>0],['Router','WiFi planned',state.settings.wifi>0],['Shield','Positive safe/day',c.safeDay>=0],['Fire Badge','3-day streak',c.streak>=3],['Visor','Meta fund',state.goals.find(g=>g.name==='Meta Glasses Fund')?.saved>0],['Plant','Under budget',c.moneyLeft>=0&&c.m.length>0]];$('itemGrid').innerHTML=items.map(([n,r,u])=>`<div class="inv-card ${u?'':'locked'}"><div class="sprite ${u?'penny':'girl'}"></div><b>${n}</b><span>${u?'Unlocked':r}</span></div>`).join('')}
function inv(n,r,sp,u){return`<div class="inv-card ${u?'':'locked'}"><div class="sprite ${sp}"></div><b>${n}</b><span>${u?'Active':r}</span></div>`}
function renderHistory(){const q=$('searchInput').value?.toLowerCase()||'',t=$('filterType').value||'all';const rows=state.entries.filter(e=>(t==='all'||e.type===t)&&(!q||`${e.title} ${e.category} ${e.note}`.toLowerCase().includes(q)));$('historyBody').innerHTML=rows.length?rows.map(e=>`<tr><td>${fmt(e.date)}</td><td>${esc(e.title)}</td><td>${esc(e.category)}</td><td>${e.type}</td><td>${money(e.amount)}</td><td><button class="del" onclick="delEntry('${e.id}')">x</button></td></tr>`).join(''):'<tr><td colspan="6">No entries</td></tr>'}
function delEntry(id){state.entries=state.entries.filter(e=>e.id!==id);recalcGoals();save();render();toast('Deleted')}
function recalcGoals(){const targets=Object.fromEntries(state.goals.map(g=>[g.name,g.target]));state.goals=clone(DEFAULT_GOALS).map(g=>({...g,target:targets[g.name]||g.target,saved:0}));const mom=state.goals.find(g=>g.name==='Mom Bucket');if(mom)mom.target=state.settings.momTarget;state.entries.filter(e=>e.type==='saving').forEach(e=>{const g=state.goals.find(x=>x.name===e.category);if(g)g.saved+=e.amount});}window.delEntry=delEntry;
function sample(){state.settings=clone(DEFAULT_SETTINGS);state.goals=clone(DEFAULT_GOALS);state.xp=2380;const data=[samp(-7,'income','Salary',60000,'Salary','Smart'),samp(-6,'expense','Rent',23000,'Rent','Necessary'),samp(-6,'expense','Furniture Rent',2000,'Furniture','Necessary'),samp(-5,'expense','Food Delivery',420,'Zomato','Worth it'),samp(-4,'expense','Transport',250,'Cab','Necessary'),samp(-3,'saving','Emergency Fund',2500,'Emergency','Smart'),samp(-2,'expense','Groceries',700,'Groceries','Necessary'),samp(-1,'saving','Mom Bucket',2000,'Mom Bucket','Smart'),samp(0,'breakfast','Office Breakfast',0,'Office breakfast','Smart')];state.entries=data;data.filter(e=>e.type==='saving').forEach(e=>{const g=state.goals.find(x=>x.name===e.category);if(g)g.saved+=e.amount});save();fillForms();render();spark();toast('Sample loaded')}
function samp(off,type,category,amount,title,label){const d=new Date();d.setDate(d.getDate()+off);return{id:crypto.randomUUID(),date:d.toISOString().slice(0,10),type,category,amount,title,label,note:''}}
function backup(){download('moneyquest-backup.json',JSON.stringify({entries:state.entries,settings:state.settings,goals:state.goals,xp:state.xp},null,2),'application/json')}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);state.entries=Array.isArray(p.entries)?p.entries:[];state.settings=p.settings||clone(DEFAULT_SETTINGS);state.goals=p.goals||clone(DEFAULT_GOALS);state.xp=+p.xp||0;save();fillForms();render();toast('Imported')}catch{toast('Import failed')}};r.readAsText(f);e.target.value=''}
function csv(){const rows=[['date','type','category','title','label','amount','note'],...state.entries.map(e=>[e.date,e.type,e.category,e.title,e.label,e.amount,e.note])];download('moneyquest-history.csv',rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}
function summary(){const c=calc();const text=`MoneyQuest Monthly Summary\n\nMoney Left: ${money(c.moneyLeft)}\nSafe/Day: ${money(Math.max(0,c.safeDay))}\nIncome: ${money(c.income)}\nFixed Left: ${money(c.fixedLeft)}\nSaved: ${money(c.personalSaved)}\nMom Bucket: ${money(c.momSaved)}\nRisk: ${c.maxRisk.status} - ${c.maxRisk.name}\n`;download('moneyquest-summary.txt',text,'text/plain')}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function resetMonth(){if(!confirm('Reset current month?'))return;state.entries=state.entries.filter(e=>!e.date.startsWith(monthKey()));recalcGoals();save();render();toast('Month reset')}
function resetAll(){if(!confirm('Reset all data?'))return;state={entries:[],settings:clone(DEFAULT_SETTINGS),goals:clone(DEFAULT_GOALS),xp:0};save();fillForms();render();toast('Reset done')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function spark(){const b=$('burst');for(let i=0;i<12;i++){const s=document.createElement('i');s.className='spark';s.style.left=(45+Math.random()*10)+'%';s.style.top=(55+Math.random()*12)+'%';s.style.animationDelay=(Math.random()*120)+'ms';b.appendChild(s);setTimeout(()=>s.remove(),1000)}}
init();
