const STORAGE_KEYS = {
  entries: 'mqp_pixel_entries_v1', settings: 'mqp_pixel_settings_v1', goals: 'mqp_pixel_goals_v1', xp: 'mqp_pixel_xp_v1'
};
const DEFAULT_SETTINGS = {
  grossSalary: 66000, inHandSalary: 60000, otherFixedIncome: 0, monthlySavingsTarget: 8000,
  fixed: { rent: 23000, furniture: 2000, wifi: 499, wifiStart: '2026-09' },
  mom: { target: 10000, protect: false },
  budgets: { foodApps: 4000, shopping: 3500, transport: 6000, other: 2500, weeklyFood: 1000, weeklySaving: 2000 }
};
const DEFAULT_GOALS = [
  { name:'Emergency Fund', target:60000, saved:0, item:'Shield' },
  { name:'Travel Fund', target:30000, saved:0, item:'Pixel Suitcase' },
  { name:'Gifts for Parents', target:12000, saved:0, item:'Heart Token' },
  { name:'Meta Glasses Fund', target:70000, saved:0, item:'Smart Visor' },
  { name:'First Salary Treats', target:6000, saved:0, item:'Celebration Aura' }
];
const LEVELS = ['Rookie Tracker','Coin Scout','Budget Fighter','Spend Slayer','Savings Knight','Cash Strategist','Risk Hunter','Money Mage','Wealth Guardian','Finance Legend'];
const CATEGORY_MAP = { expense:['Food Delivery','Office Food','Groceries','Transport','Rent','Furniture Rent','WiFi','Electricity','Appliances','Mom','Shopping','Health','Beauty','Travel','Other'], income:['Salary','Refund','Transfer In','Other Income'], saving:DEFAULT_GOALS.map(g=>g.name), breakfast:['Office Breakfast'] };
const COLORS = { t:'transparent', k:'#070a16', w:'#fff4db', c:'#d49a5e', b:'#8a5637', p:'#ff9acb', y:'#ffd76a', g:'#67ef9a', d:'#1d2a4f', n:'#50e6ff', v:'#8b6dff', r:'#ff637d', m:'#10162c', o:'#ffb15d', q:'#f5f7ff' };
const SPRITES = {
  mochi:['tttkkkkttt','ttkccccktt','tkcwwwwckt','tkcwcwcwkt','tccwwbwwct','tccwwwwcct','ttccyycctt','ttcccccttt','tbccttccb t'.replace(/ /g,''),'tbbttttbbt'],
  panda:['ttkkkkkttt','tkkwwwwktt','tkwwkkwwkt','tkwkwkwwkt','tkkwwwwktt','ttkgggkttt','ttkgggkttt','ttkkkkt ttt'.replace(/ /g,''),'ttktttkttt','ttktttkttt'],
  penny:['tttyyytttt','ttynyntttt','ttywywtttt','tttppptttt','tnppgppntt','tttpgptttt','tttpgptttt','ttnytynttt','tntttttntt','tttttttttt'],
  snack:['tttrrrrttt','ttrororrtt','trowwwortt','trwwwwwrtt','trwwwwwrtt','ttroorrttt','ttooyyoott','ttyttttytt','tttttttttt','tttttttttt'],
  shopping:['tttvvvtttt','ttvgggvttt','tvgygygvtt','tvgggggvtt','ttvpppvttt','tppvvvpp t'.replace(/ /g,''),'tppvvvpp t'.replace(/ /g,''),'ttvtttvttt','ttgtttgttt','tttttttttt'],
  cab:['tttyyyyttt','ttykkkyytt','tyynynnyyt','tyyyyyyyyt','tykkyykky t'.replace(/ /g,''),'tyyyyyyyyt','ttyyttyytt','tttttttttt','tttttttttt','tttttttttt'],
  dragon:['tttggggttt','ttgrggrgtt','tgggggggtt','tggrggggtt','ttgggggttt','ttvgggvttt','tvvgggvvtt','tttggttttt','ttgttgtttt','tttttttttt'],
  owl:['tttddddttt','ttdyyyydtt','tdywywydtt','tdyykyydtt','ttdyuydttt','ttdvvvdttt','tttvvvtttt','ttdtttdttt','tttttttttt','tttttttttt'],
  squirrel:['tttoootttt','ttooooottt','toyoyoottt','tooookottt','tttooott t'.replace(/ /g,''),'ttoooo ttt'.replace(/ /g,''),'toootoottt','tottttottt','tttttttttt','tttttttttt']
};
const CHARACTERS = [
  {id:'mochi', name:'Mochi', subtitle:'Money Pup', role:'Main companion', unlock:'Always active', test:()=>true},
  {id:'panda', name:'Panda Pockets', subtitle:'Balance Guide', role:'Appears when your protected budget is positive.', unlock:'Stay under budget', test:m=>m.projectedEnd>=0 && m.monthEntries.length>0},
  {id:'penny', name:'Penny', subtitle:'Coin Fairy', role:'Savings helper for vault progress.', unlock:'First saving', test:m=>m.saved>0},
  {id:'snack', name:'Snack Monster', subtitle:'Food Risk', role:'Grows with food app spending.', unlock:'Food app spend appears', test:m=>m.foodApps>0},
  {id:'shopping', name:'Shopping Goblin', subtitle:'Impulse Risk', role:'Grows with shopping and regret tags.', unlock:'Shopping spend appears', test:m=>(m.categoryTotals.Shopping||0)>0},
  {id:'cab', name:'Cab Beast', subtitle:'Commute Risk', role:'Grows with transport spending.', unlock:'Transport spend appears', test:m=>(m.categoryTotals.Transport||0)>0},
  {id:'dragon', name:'Bill Dragon', subtitle:'Fixed Boss', role:'Tracks protected rent, furniture and WiFi.', unlock:'Fixed costs active', test:m=>m.protectedFixed>0},
  {id:'owl', name:'Budget Owl', subtitle:'Insight Guide', role:'Explains warnings and projections.', unlock:'Any risk appears', test:m=>m.alerts.length>0},
  {id:'squirrel', name:'Streak Squirrel', subtitle:'Habit Tracker', role:'Tracks daily log streaks.', unlock:'3-day streak', test:m=>m.streak>=3}
];
const BADGES = [
  {id:'firstLog', title:'First Log', item:'Receipt Card', test:m=>m.entries.length>0},
  {id:'firstSave', title:'First Saving', item:'Coin Pouch', test:m=>m.saved>0},
  {id:'rent', title:'Rent Planned', item:'House Token', test:m=>m.settings.fixed.rent>0},
  {id:'streak3', title:'3-Day Streak', item:'Fire Badge', test:m=>m.streak>=3},
  {id:'noFood', title:'No Food-App Day', item:'Snack Shield', test:m=>m.todayLogged && m.todayFoodApps===0},
  {id:'underBudget', title:'Positive Projection', item:'Panda Badge', test:m=>m.projectedEnd>=0 && m.monthEntries.length>0},
  {id:'saveTarget', title:'Savings Target Hit', item:'Golden Aura', test:m=>m.saved>=m.settings.monthlySavingsTarget},
  {id:'momBucket', title:'Family Bucket Started', item:'Heart Token', test:m=>m.momSent>0}
];
let state = { entries: load(STORAGE_KEYS.entries, []), settings: load(STORAGE_KEYS.settings, DEFAULT_SETTINGS), goals: load(STORAGE_KEYS.goals, DEFAULT_GOALS), xp: load(STORAGE_KEYS.xp, 0) };
const el = {};
function $(id){return document.getElementById(id)}
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v ?? clone(f)}catch{return clone(f)}}
function saveAll(){localStorage.setItem(STORAGE_KEYS.entries,JSON.stringify(state.entries));localStorage.setItem(STORAGE_KEYS.settings,JSON.stringify(state.settings));localStorage.setItem(STORAGE_KEYS.goals,JSON.stringify(state.goals));localStorage.setItem(STORAGE_KEYS.xp,JSON.stringify(state.xp))}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0)}
function sum(a){return a.reduce((x,y)=>x+Number(y||0),0)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function monthKey(d=new Date()){return d.toISOString().slice(0,7)}
function formatDate(d){return new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function escapeHtml(t=''){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function activeWifi(){return monthKey(new Date()) >= state.settings.fixed.wifiStart}
function init(){['sampleBtn','csvBtn','exportBtn','importInput','resetAllBtn','resetMonthBtn','summaryBtn','entryForm','entryDate','entryType','entryCategory','entryAmount','entryTitle','entryLabel','entryNote','goalForm','goalName','goalAmount','momForm','momAmount','momNote','settingsForm','budgetForm','grossSalaryInput','inHandSalaryInput','otherIncomeInput','monthlySavingsTargetInput','rentInput','furnitureInput','wifiInput','wifiStartInput','momTargetInput','protectMomInput','foodBudgetInput','shoppingBudgetInput','transportBudgetInput','otherBudgetInput','weeklyFoodInput','weeklySavingInput','searchInput','filterType','toast'].forEach(id=>el[id]=$(id));document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>switchScreen(btn.dataset.screen,btn)));el.entryType.addEventListener('change',populateCategories);el.entryForm.addEventListener('submit',handleEntry);el.goalForm.addEventListener('submit',handleGoal);el.momForm.addEventListener('submit',handleMom);el.settingsForm.addEventListener('submit',handleSettings);el.budgetForm.addEventListener('submit',handleBudgets);el.sampleBtn.addEventListener('click',loadSample);el.csvBtn.addEventListener('click',exportCSV);el.exportBtn.addEventListener('click',exportBackup);el.importInput.addEventListener('change',importBackup);el.resetAllBtn.addEventListener('click',resetAll);el.resetMonthBtn.addEventListener('click',resetCurrentMonth);el.summaryBtn.addEventListener('click',downloadSummary);el.searchInput.addEventListener('input',renderHistory);el.filterType.addEventListener('change',renderHistory);document.querySelectorAll('.quick-btn').forEach(btn=>btn.addEventListener('click',()=>addEntry({id:crypto.randomUUID(),date:todayKey(),type:btn.dataset.type,category:btn.dataset.category,title:btn.dataset.title,amount:Number(btn.dataset.amount),label:btn.dataset.label,note:'Quick log'})));populateCategories();populateGoals();fillSettings();el.entryDate.value=todayKey();render()}
function switchScreen(id,btn){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function populateCategories(){el.entryCategory.innerHTML=CATEGORY_MAP[el.entryType.value].map(c=>`<option value="${c}">${c}</option>`).join('')}
function populateGoals(){el.goalName.innerHTML=state.goals.map(g=>`<option value="${g.name}">${g.name}</option>`).join('')}
function fillSettings(){const s=state.settings;el.grossSalaryInput.value=s.grossSalary;el.inHandSalaryInput.value=s.inHandSalary;el.otherIncomeInput.value=s.otherFixedIncome;el.monthlySavingsTargetInput.value=s.monthlySavingsTarget;el.rentInput.value=s.fixed.rent;el.furnitureInput.value=s.fixed.furniture;el.wifiInput.value=s.fixed.wifi;el.wifiStartInput.value=s.fixed.wifiStart;el.momTargetInput.value=s.mom.target;el.protectMomInput.checked=!!s.mom.protect;el.foodBudgetInput.value=s.budgets.foodApps;el.shoppingBudgetInput.value=s.budgets.shopping;el.transportBudgetInput.value=s.budgets.transport;el.otherBudgetInput.value=s.budgets.other;el.weeklyFoodInput.value=s.budgets.weeklyFood;el.weeklySavingInput.value=s.budgets.weeklySaving}
function sprite(id,size='lg',extra=''){const arr=SPRITES[id]||SPRITES.mochi;let h=`<div class="pixel-sprite sprite-${size} ${extra}" style="--cols:${arr[0].length}">`;for(const row of arr){for(const ch of row){h+=`<span class="px" style="background:${COLORS[ch]||'transparent'}"></span>`}}return h+'</div>'}
function handleEntry(e){e.preventDefault();const entry={id:crypto.randomUUID(),date:el.entryDate.value,type:el.entryType.value,category:el.entryCategory.value,amount:Number(el.entryAmount.value),title:el.entryTitle.value.trim(),label:el.entryLabel.value,note:el.entryNote.value.trim()};if(!entry.title||entry.amount<0){toast('Add valid title and amount.');return}addEntry(entry);el.entryForm.reset();el.entryDate.value=todayKey();el.entryType.value='expense';populateCategories()}
function addEntry(entry){state.entries.unshift(entry);if(entry.type==='saving'){const g=state.goals.find(x=>x.name===entry.category);if(g)g.saved+=entry.amount}const xp=xpFor(entry);state.xp+=xp;saveAll();render();fxXP(xp);if(entry.type==='saving')fxCoins();toast(`Logged +${xp} XP`)}
function xpFor(e){let xp=20;if(e.type==='saving')xp+=45;if(e.type==='income')xp+=35;if(e.label==='Smart')xp+=20;if(e.label==='Necessary')xp+=10;if(e.category==='Rent'||e.category==='Furniture Rent'||e.category==='WiFi')xp+=20;if(e.category==='Mom')xp+=25;if(e.label==='Impulse'||e.label==='Regret')xp-=5;return Math.max(5,xp)}
function handleGoal(e){e.preventDefault();const amount=Number(el.goalAmount.value||0);if(amount<=0){toast('Enter saving amount.');return}addEntry({id:crypto.randomUUID(),date:todayKey(),type:'saving',category:el.goalName.value,title:`${el.goalName.value} saving`,amount,label:'Smart',note:'Vault saving'});el.goalAmount.value=''}
function handleMom(e){e.preventDefault();const amount=Number(el.momAmount.value||0);if(amount<=0){toast('Enter amount.');return}addEntry({id:crypto.randomUUID(),date:todayKey(),type:'expense',category:'Mom',title:'Mom contribution',amount,label:'Smart',note:el.momNote.value.trim()||'Family bucket'});el.momAmount.value='';el.momNote.value=''}
function handleSettings(e){e.preventDefault();state.settings.grossSalary=Number(el.grossSalaryInput.value||0);state.settings.inHandSalary=Number(el.inHandSalaryInput.value||0);state.settings.otherFixedIncome=Number(el.otherIncomeInput.value||0);state.settings.monthlySavingsTarget=Number(el.monthlySavingsTargetInput.value||0);state.settings.fixed.rent=Number(el.rentInput.value||0);state.settings.fixed.furniture=Number(el.furnitureInput.value||0);state.settings.fixed.wifi=Number(el.wifiInput.value||0);state.settings.fixed.wifiStart=el.wifiStartInput.value||'2026-09';state.settings.mom.target=Number(el.momTargetInput.value||0);state.settings.mom.protect=!!el.protectMomInput.checked;saveAll();render();toast('Core settings saved.')}
function handleBudgets(e){e.preventDefault();const b=state.settings.budgets;b.foodApps=Number(el.foodBudgetInput.value||0);b.shopping=Number(el.shoppingBudgetInput.value||0);b.transport=Number(el.transportBudgetInput.value||0);b.other=Number(el.otherBudgetInput.value||0);b.weeklyFood=Number(el.weeklyFoodInput.value||0);b.weeklySaving=Number(el.weeklySavingInput.value||0);saveAll();render();toast('Category budgets saved.')}
function monthEntries(){return state.entries.filter(e=>e.date.startsWith(monthKey()))}
function calcStreak(){const dates=[...new Set(state.entries.map(e=>e.date))].sort().reverse();let s=0,d=new Date();while(true){const k=d.toISOString().slice(0,10);if(dates.includes(k)){s++;d.setDate(d.getDate()-1)}else break}return s}
function daysLeft(){const d=new Date();const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return Math.max(1,last-d.getDate()+1)}
function metrics(){const entries=state.entries,me=monthEntries(),incomeEntries=me.filter(e=>e.type==='income'),expenseEntries=me.filter(e=>e.type==='expense'||e.type==='breakfast'),savingEntries=me.filter(e=>e.type==='saving');const income=state.settings.inHandSalary+state.settings.otherFixedIncome+sum(incomeEntries.map(e=>e.amount));const saved=sum(savingEntries.map(e=>e.amount));const allSpent=sum(expenseEntries.map(e=>e.amount));const categoryTotals={};expenseEntries.forEach(e=>categoryTotals[e.category]=(categoryTotals[e.category]||0)+e.amount);const fixedCats=['Rent','Furniture Rent','WiFi'];const fixedLogged=sum(expenseEntries.filter(e=>fixedCats.includes(e.category)).map(e=>e.amount));const variableSpent=allSpent-fixedLogged;const protectedFixed=state.settings.fixed.rent+state.settings.fixed.furniture+(activeWifi()?state.settings.fixed.wifi:0);const momSent=categoryTotals.Mom||0;const momRemaining=Math.max(0,state.settings.mom.target-momSent);const protectedMom=state.settings.mom.protect?momRemaining:0;const remainingSavings=Math.max(0,state.settings.monthlySavingsTarget-saved);const safePool=income-protectedFixed-protectedMom-remainingSavings-variableSpent;const dailySafe=Math.max(0,safePool/daysLeft());const projectedEnd=safePool;const moneyLeftActual=income-allSpent-saved;const foodApps=sum(me.filter(e=>/zomato|zepto|blinkit|food delivery/i.test(`${e.title} ${e.category}`)).map(e=>e.amount));const todayEntries=entries.filter(e=>e.date===todayKey());const todayLogged=todayEntries.length>0;const todayFoodApps=sum(todayEntries.filter(e=>/zomato|zepto|blinkit|food delivery/i.test(`${e.title} ${e.category}`)).map(e=>e.amount));const impulseCount=me.filter(e=>e.label==='Impulse'||e.label==='Regret').length;const streak=calcStreak();const monsters=buildMonsters(categoryTotals,foodApps,protectedFixed);const activeMonster=monsters.reduce((a,b)=>b.rawPct>a.rawPct?b:a,{name:'None',rawPct:0,id:'mochi'});let score=64;if(todayLogged)score+=9;else score-=12;if(streak>=5)score+=9;else if(streak>=3)score+=6;if(projectedEnd>=0)score+=8;else score-=24;if(saved>=state.settings.monthlySavingsTarget)score+=15;else if(saved>0)score+=7;if(foodApps>state.settings.budgets.foodApps)score-=10;if(impulseCount>2)score-=6;if(impulseCount>5)score-=10;score=Math.max(0,Math.min(100,Math.round(score)));const alerts=makeAlerts({income,saved,allSpent,categoryTotals,variableSpent,protectedFixed,protectedMom,remainingSavings,safePool,dailySafe,projectedEnd,moneyLeftActual,foodApps,todayEntries,todayLogged,todayFoodApps,impulseCount,streak,monsters,activeMonster});return {entries,settings:state.settings,monthEntries:me,income,saved,allSpent,categoryTotals,variableSpent,protectedFixed,protectedMom,momSent,momRemaining,remainingSavings,safePool,dailySafe,projectedEnd,moneyLeftActual,foodApps,todayEntries,todayLogged,todayFoodApps,impulseCount,streak,monsters,activeMonster,score,alerts}}
function buildMonsters(totals,foodApps,protectedFixed){const b=state.settings.budgets;const list=[{id:'snack',sprite:'snack',name:'Snack Monster',spent:foodApps,limit:b.foodApps,mission:'No food delivery day or keep weekly food apps under limit.'},{id:'shopping',sprite:'shopping',name:'Shopping Goblin',spent:totals.Shopping||0,limit:b.shopping,mission:'Use 24-hour wait rule and avoid impulse tags.'},{id:'cab',sprite:'cab',name:'Cab Beast',spent:totals.Transport||0,limit:b.transport,mission:'Use public transport day and stay under commute budget.'},{id:'dragon',sprite:'dragon',name:'Bill Dragon',spent:protectedFixed,limit:protectedFixed||1,mission:'Protected fixed costs: rent, furniture, WiFi if active.'},{id:'chaos',sprite:'snack',name:'Chaos Blob',spent:(totals.Other||0)+(totals.Beauty||0)+(totals['Office Food']||0),limit:b.other,mission:'Categorise spends and reduce random/regret expenses.'}];return list.map(x=>{const rawPct=x.limit?Math.round(x.spent/x.limit*100):0;let stage='Dormant',cls='dormant';if(rawPct>=100){stage='Boss Mode';cls='boss'}else if(rawPct>=75){stage='Angry';cls='angry'}else if(rawPct>0){stage='Growing';cls='growing'}return {...x,rawPct,pct:Math.min(100,rawPct),stage,cls}})}
function makeAlerts(m){const arr=[];if(m.projectedEnd<0)arr.push(['Critical','Your projected end balance is negative after fixed costs, savings target and variable spend.']);else arr.push(['Safe spend',`You can spend ${money(m.dailySafe)} per day and keep protected costs plus savings covered.`]);if(!activeWifi())arr.push(['WiFi rule',`WiFi is not counted yet. It starts from ${state.settings.fixed.wifiStart} at ${money(state.settings.fixed.wifi)}.`]);if(state.settings.mom.protect)arr.push(['Mom protected',`Mom bucket remaining ${money(m.momRemaining)} is included in daily safe spend.`]);else arr.push(['Mom separate','Mom contribution is tracked as a family bucket, not fixed expenditure.']);if(m.foodApps>state.settings.budgets.foodApps)arr.push(['Food risk','Food app spend crossed your monthly food-app budget.']);if(m.impulseCount>2)arr.push(['Impulse risk',`${m.impulseCount} impulse/regret entries are increasing risk.`]);return arr}
function levelInfo(){const level=Math.min(10,Math.floor(state.xp/1000)+1),start=(level-1)*1000,current=Math.min(1000,state.xp-start);return {level,title:LEVELS[level-1],current,needed:1000,pct:Math.max(0,Math.min(100,current/1000*100))}}
function render(){populateGoals();fillSettings();const m=metrics(),lv=levelInfo();renderHome(m,lv);renderEntries(m);renderArena(m);renderMissions(m);renderVault(m);renderTerminal(m);renderInventory(m);renderHistory()}
function renderHome(m,lv){$('sideLevel').textContent=`LV ${lv.level}`;$('sideTitle').textContent=lv.title;$('sideXpFill').style.width=`${lv.pct}%`;$('baseHeadline').textContent=headline(m,lv);$('baseSubline').textContent=subline(m);$('healthScore').textContent=m.score;$('rankText').textContent=`LV ${lv.level} · ${lv.title}`;$('xpNumber').textContent=`${state.xp.toLocaleString('en-IN')} XP`;$('xpFill').style.width=`${lv.pct}%`;$('dailySafeHero').textContent=money(m.dailySafe);$('moneyLeftHero').textContent=money(m.moneyLeftActual);$('fixedHero').textContent=money(m.protectedFixed);$('savedHero').textContent=money(m.saved);$('incomeStat').textContent=money(m.income);$('variableStat').textContent=money(m.variableSpent);$('projectedStat').textContent=money(m.projectedEnd);$('riskStat').textContent=m.activeMonster.name;const stage=$('gameStage');stage.className='game-stage '+(m.projectedEnd<0||m.score<40?'state-danger':m.score>=75?'state-good':'state-neutral');$('mainPetSprite').innerHTML=sprite('mochi','xl',petClass(m));$('activeHelperSprite').innerHTML=sprite(activeHelper(m).id,'lg');$('activeMonsterSprite').innerHTML=m.activeMonster.id==='None'?sprite('owl','lg'):sprite(m.activeMonster.sprite||'snack','lg');renderAccessories(m,lv);$('todayMissionPreview').innerHTML=dailyMissions(m).slice(0,4).map(missionCard).join('');$('riskAlerts').innerHTML=m.alerts.slice(0,5).map(([h,p])=>`<div class="info-card"><h4>${h}</h4><p>${p}</p></div>`).join('')}
function headline(m,lv){if(m.projectedEnd<0)return 'Boss threat detected';if(!m.todayLogged)return 'Mochi is offline';if(m.saved>=m.settings.monthlySavingsTarget)return 'Vault target cleared';return `Rank ${lv.level}: ${lv.title}`}
function subline(m){if(m.projectedEnd<0)return 'Reduce variable spends or lower target to restore safe spend.';if(!m.todayLogged)return 'Log today to activate streak and XP.';return `Safe spend engine allows ${money(m.dailySafe)} per day.`}
function petClass(m){if(m.projectedEnd<0||m.score<40)return 'pet-stressed';if(!m.todayLogged)return 'pet-sleepy';if(m.saved>=m.settings.monthlySavingsTarget)return 'pet-excited';if(m.score>=75)return 'pet-happy';return 'pet-idle'}
function activeHelper(m){if(m.streak>=3)return {id:'squirrel'};if(m.projectedEnd>=0&&m.monthEntries.length)return {id:'panda'};if(m.saved>0)return {id:'penny'};return {id:'owl'}}
function renderAccessories(m,lv){const parts=[];if(m.saved>0)parts.push('<div class="item-shield"></div>');if((state.goals.find(g=>g.name==='Meta Glasses Fund')?.saved||0)>0)parts.push('<div class="item-glasses"></div>');if(lv.level>=8||m.saved>=m.settings.monthlySavingsTarget)parts.push('<div class="item-crown"></div>');$('petAccessoryLayer').innerHTML=parts.join('')}
function renderEntries(m){$('recentEntries').innerHTML=state.entries.length?state.entries.slice(0,10).map(entryCard).join(''):emptyCard('No logs yet','Your receipts will appear here.')}
function entryCard(e){return `<div class="entry-card"><div class="entry-line"><div><div class="entry-title">${escapeHtml(e.title)}</div><div class="entry-meta">${formatDate(e.date)} · ${escapeHtml(e.category)} · ${escapeHtml(e.label)}</div></div><strong class="entry-amount ${e.type}">${(e.type==='expense'||e.type==='breakfast')?'-':'+'}${money(e.amount)}</strong></div><div class="entry-line"><span class="entry-meta">${escapeHtml(e.note||e.type)}</span><button class="delete-btn" onclick="deleteEntry('${e.id}')">Delete</button></div></div>`}
function emptyCard(t,p){return `<div class="entry-card"><h4>${t}</h4><p>${p}</p></div>`}
function renderArena(m){$('monsterGrid').innerHTML=m.monsters.map(x=>`<div class="monster-card ${x.cls}"><div class="monster-avatar">${sprite(x.sprite||x.id,'lg')}</div><div class="monster-top"><div><h4>${x.name}</h4><p>${x.stage} · ${money(x.spent)} / ${money(x.limit)}</p></div><strong>${x.rawPct}%</strong></div><div class="progress"><div style="width:${x.pct}%"></div></div><p>${x.mission}</p></div>`).join('')}
function dailyMissions(m){return [{title:'Log today',xp:20,done:m.todayLogged,text:'Add at least one entry.'},{title:'Stay under safe spend',xp:30,done:m.todayLogged && sum(m.todayEntries.filter(e=>e.type==='expense'||e.type==='breakfast').map(e=>e.amount))<=m.dailySafe,text:`Today safe spend: ${money(m.dailySafe)}.`},{title:'No food-app day',xp:25,done:m.todayLogged&&m.todayFoodApps===0,text:'No Zomato/Zepto/Blinkit today.'},{title:'No impulse tag',xp:30,done:m.todayLogged&&!m.todayEntries.some(e=>e.label==='Impulse'||e.label==='Regret'),text:'Avoid impulse/regret entries.'},{title:'Add saving',xp:40,done:m.todayEntries.some(e=>e.type==='saving'),text:'Add one saving entry.'}]}
function weeklyMissions(m){const week=last7Entries(),weekFood=sum(week.filter(e=>/zomato|zepto|blinkit|food delivery/i.test(`${e.title} ${e.category}`)).map(e=>e.amount)),weekSaved=sum(week.filter(e=>e.type==='saving').map(e=>e.amount)),weekImpulse=week.filter(e=>e.label==='Impulse'||e.label==='Regret').length,weekTransport=sum(week.filter(e=>e.category==='Transport').map(e=>e.amount));return [{title:'5-day streak',xp:150,done:m.streak>=5,text:`Current streak: ${m.streak}.`},{title:'Food apps under weekly limit',xp:100,done:week.length>0&&weekFood<=m.settings.budgets.weeklyFood,text:`Weekly food apps: ${money(weekFood)} / ${money(m.settings.budgets.weeklyFood)}.`},{title:'Save weekly mission',xp:120,done:weekSaved>=m.settings.budgets.weeklySaving,text:`Weekly savings: ${money(weekSaved)} / ${money(m.settings.budgets.weeklySaving)}.`},{title:'No impulse week',xp:120,done:week.length>0&&weekImpulse===0,text:`Impulse/regret count: ${weekImpulse}.`},{title:'Transport control',xp:80,done:week.length>0&&weekTransport<=m.settings.budgets.transport/4,text:`Weekly transport: ${money(weekTransport)}.`}]}
function last7Entries(){const set=new Set();for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);set.add(d.toISOString().slice(0,10))}return state.entries.filter(e=>set.has(e.date))}
function missionCard(q){return `<div class="mission-card ${q.done?'done':''}"><div class="mission-top"><div><h4>${q.done?'CLEAR':'OPEN'} · ${q.title}</h4><p>${q.text}</p></div><strong>+${q.xp} XP</strong></div></div>`}
function renderMissions(m){$('dailyMissions').innerHTML=dailyMissions(m).map(missionCard).join('');$('weeklyMissions').innerHTML=weeklyMissions(m).map(missionCard).join('')}
function renderVault(m){$('goalGrid').innerHTML=state.goals.map(g=>{const pct=Math.min(100,Math.round(g.saved/g.target*100));return `<div class="goal-card"><div class="goal-top"><div><h4>${g.name}</h4><p>Item: ${g.item}</p></div><strong>${pct}%</strong></div><p>${money(g.saved)} / ${money(g.target)}</p><div class="progress"><div style="width:${pct}%"></div></div></div>`}).join('');$('momBucket').innerHTML=`<div class="term-card ${m.momSent>=m.settings.mom.target?'good':'warning'}"><span>MOM CONTRIBUTION</span><strong>${money(m.momSent)} / ${money(m.settings.mom.target)}</strong><p>Separate family bucket. ${m.settings.mom.protect?'Protected in daily safe spend.':'Not included in fixed expenditure.'}</p><div class="progress"><div style="width:${Math.min(100,Math.round(m.momSent/Math.max(1,m.settings.mom.target)*100))}%"></div></div></div>`}
function renderTerminal(m){const cells=[['Income available',money(m.income),'In-hand + extra income','good'],['Protected fixed',money(m.protectedFixed),'Rent + furniture + WiFi if active','warning'],['Rent',money(m.settings.fixed.rent),'Fixed protected cost',''],['Furniture rent',money(m.settings.fixed.furniture),'Fixed protected cost',''],['WiFi status',activeWifi()?money(m.settings.fixed.wifi):'₹0',`Starts from ${m.settings.fixed.wifiStart}`,''],['Savings still required',money(m.remainingSavings),'Target minus saved','warning'],['Variable spent',money(m.variableSpent),'Logged spending excluding protected fixed',''],['Mom protected',money(m.protectedMom),m.settings.mom.protect?'Included in safe spend':'Not included',''],['Daily safe spend',money(m.dailySafe),'Safe amount per remaining day',m.dailySafe>0?'good':'danger'],['Projected end balance',money(m.projectedEnd),'After protected costs, savings and variable spend',m.projectedEnd>=0?'good':'danger'],['Actual money left',money(m.moneyLeftActual),'Based only on logged entries',''],['Days left',String(daysLeft()),'Current month','']];$('terminalGrid').innerHTML=cells.map(([a,b,c,cls])=>`<div class="term-card ${cls}"><span>${a}</span><strong>${b}</strong><p>${c}</p></div>`).join('');const boss=m.activeMonster.name==='None'?{name:'No Boss',stage:'Controlled',mission:'Keep logging to maintain control.',sprite:'panda'}:m.activeMonster;$('bossCard').innerHTML=`<div class="monster-avatar">${sprite(boss.sprite||'panda','lg')}</div><h4>${boss.name}</h4><p>Month-end boss: ${boss.stage||'Controlled'}</p><p>${boss.mission||'No major threat currently.'}</p><div class="progress"><div style="width:${Math.min(100,boss.rawPct||0)}%"></div></div>`}
function renderInventory(m){$('characterGrid').innerHTML=CHARACTERS.map(c=>{const ok=c.test(m);return `<div class="character-card ${ok?'':'locked'}"><div class="character-avatar">${sprite(c.id==='dragon'?'dragon':c.id,'lg')}</div><h4>${c.name}</h4><p>${c.subtitle}</p><p>${c.role}</p><p>${ok?'UNLOCKED':'LOCKED'} · ${c.unlock}</p></div>`}).join('');$('badgeGrid').innerHTML=BADGES.map(b=>{const ok=b.test(m);return `<div class="badge-card ${ok?'unlocked':'locked'}"><h4>${b.title}</h4><p>Item: ${b.item}</p><p>${ok?'UNLOCKED':'LOCKED'}</p></div>`}).join('')}
function renderHistory(){const q=el.searchInput.value.trim().toLowerCase(),type=el.filterType.value;const rows=state.entries.filter(e=>(!q||e.title.toLowerCase().includes(q)||e.category.toLowerCase().includes(q)||(e.note||'').toLowerCase().includes(q))&&(type==='all'||e.type===type));$('historyBody').innerHTML=rows.length?rows.map(e=>`<tr><td>${formatDate(e.date)}</td><td>${escapeHtml(e.title)}<div class="entry-meta">${escapeHtml(e.note||'')}</div></td><td>${escapeHtml(e.category)}</td><td>${e.type}</td><td>${escapeHtml(e.label)}</td><td class="entry-amount ${e.type}">${(e.type==='expense'||e.type==='breakfast')?'-':'+'}${money(e.amount)}</td><td><button class="delete-btn" onclick="deleteEntry('${e.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No entries found.</td></tr>'}
function deleteEntry(id){const e=state.entries.find(x=>x.id===id);if(e&&e.type==='saving'){const g=state.goals.find(x=>x.name===e.category);if(g)g.saved=Math.max(0,g.saved-e.amount)}state.entries=state.entries.filter(x=>x.id!==id);saveAll();render();toast('Entry deleted.')}window.deleteEntry=deleteEntry;
function fxXP(xp){const p=$('xpPopup');p.textContent=`+${xp} XP`;p.classList.remove('show');void p.offsetWidth;p.classList.add('show')}
function fxCoins(){const layer=$('fxLayer');for(let i=0;i<18;i++){const coin=document.createElement('div');coin.className='coin-fx';coin.style.left=`${38+Math.random()*24}%`;coin.style.top=`${125+Math.random()*45}px`;coin.style.animationDelay=`${Math.random()*0.2}s`;layer.appendChild(coin);setTimeout(()=>coin.remove(),1350)}}
function exportCSV(){const header=['date','type','category','title','label','amount','note'];const rows=state.entries.map(e=>header.map(h=>`"${String(e[h]??'').replaceAll('"','""')}"`).join(','));download('money-quest-pixel-history.csv',[header.join(','),...rows].join('\n'),'text/csv')}
function downloadSummary(){const m=metrics();const text=`MoneyQuest OS Monthly Summary\nMonth: ${monthKey()}\n\nIncome: ${money(m.income)}\nProtected fixed: ${money(m.protectedFixed)}\nVariable spent: ${money(m.variableSpent)}\nSavings: ${money(m.saved)}\nRemaining savings target: ${money(m.remainingSavings)}\nDaily safe spend: ${money(m.dailySafe)}\nProjected end balance: ${money(m.projectedEnd)}\nMom contribution: ${money(m.momSent)} / ${money(m.settings.mom.target)}\nActive risk: ${m.activeMonster.name}\nXP: ${state.xp}\nStreak: ${m.streak} days\n\nAlerts:\n${m.alerts.map(a=>'- '+a[0]+': '+a[1]).join('\n')}`;download('money-quest-monthly-summary.txt',text,'text/plain')}
function exportBackup(){download('money-quest-pixel-backup.json',JSON.stringify({entries:state.entries,settings:state.settings,goals:state.goals,xp:state.xp},null,2),'application/json')}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function importBackup(ev){const file=ev.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);state.entries=Array.isArray(p.entries)?p.entries:[];state.settings={...clone(DEFAULT_SETTINGS),...(p.settings||{})};state.settings.fixed={...clone(DEFAULT_SETTINGS.fixed),...(p.settings?.fixed||{})};state.settings.mom={...clone(DEFAULT_SETTINGS.mom),...(p.settings?.mom||{})};state.settings.budgets={...clone(DEFAULT_SETTINGS.budgets),...(p.settings?.budgets||{})};state.goals=p.goals||clone(DEFAULT_GOALS);state.xp=Number(p.xp||0);saveAll();populateGoals();fillSettings();render();toast('Backup imported.')}catch{toast('Could not import file.')}};r.readAsText(file);ev.target.value=''}
function resetCurrentMonth(){if(!confirm('Reset current month entries only?'))return;const mk=monthKey();state.entries=state.entries.filter(e=>!e.date.startsWith(mk));state.goals=clone(DEFAULT_GOALS);saveAll();render();toast('Current month reset.')}
function resetAll(){if(!confirm('Reset all app data?'))return;state.entries=[];state.settings=clone(DEFAULT_SETTINGS);state.goals=clone(DEFAULT_GOALS);state.xp=0;saveAll();populateGoals();fillSettings();render();toast('All data reset.')}
function sample(offset,type,category,amount,title,label,note=''){const d=new Date();d.setDate(d.getDate()+offset);return{id:crypto.randomUUID(),date:d.toISOString().slice(0,10),type,category,amount,title,label,note}}
function loadSample(){state.settings=clone(DEFAULT_SETTINGS);state.goals=clone(DEFAULT_GOALS);state.xp=2420;const es=[sample(-7,'income','Salary',60000,'Salary credited','Smart'),sample(-7,'expense','Rent',23000,'Rent planned','Necessary'),sample(-6,'expense','Mom',5000,'Mom contribution','Smart'),sample(-6,'expense','Groceries',540,'Zepto groceries','Necessary'),sample(-5,'expense','Food Delivery',360,'Zomato dinner','Worth it'),sample(-5,'breakfast','Office Breakfast',90,'Office coffee','Worth it'),sample(-4,'expense','Transport',250,'Cab and metro','Necessary'),sample(-4,'saving','Emergency Fund',2500,'Emergency saving','Smart'),sample(-3,'saving','Travel Fund',1500,'Travel fund saving','Smart'),sample(-2,'expense','Shopping',699,'Impulse treat','Impulse'),sample(-1,'expense','Furniture Rent',2000,'Furniture rent','Necessary'),sample(0,'breakfast','Office Breakfast',0,'Office free breakfast','Smart')];es.filter(e=>e.type==='saving').forEach(e=>{const g=state.goals.find(x=>x.name===e.category);if(g)g.saved+=e.amount});state.entries=es;saveAll();render();fxCoins();fxXP(150);toast('Sample data loaded.')}
function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove('show'),2300)}
init();
